name: capital-bikeshare-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.3.0
  - numpy=2.3.0
  - folium=0.19.7
  - geopandas=1.1.0
  - shapely=2.1.1
  - geopy=2.4.1
  - jupyterlab
